# Cloudflare Pages Configuration
# Configuración específica para deployment en Cloudflare Pages

name = "ecoswap"
compatibility_date = "2024-01-01"

# Configuración específica para Pages
pages_build_output_dir = "out"

# Variables de entorno para producción
[vars]
NODE_ENV = "production"
NEXT_PUBLIC_APP_ENV = "production"
